[package]
name = "web_scraper"
version = "0.1.0"
edition = "2021"

[dependencies]
regex = "1.10.5"
reqwest = { version = "0.12", features = ["json"] }
tokio = { version = "1", features = ["full"] }
tokio-stream = "0.1.15"
scraper = "0.19"
